apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-frontend
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
