apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-backend
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
